// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type Customer struct {
	ID        uuid.UUID
	CreatedAt time.Time
	UpdatedAt time.Time
	Email     string
	Password  string
}

type Order struct {
	OrderID    int64
	CustomerID uuid.UUID
	CreatedAt  sql.NullTime
}

type OrderItem struct {
	ID        int64
	OrderID   int64
	ProductID int64
	Quantity  int32
	Price     string
	Subtotal  sql.NullString
}

type Product struct {
	ID          int64
	Name        string
	Price       string
	Quantity    int32
	Description string
	CreatedAt   time.Time
	UpdatedAt   time.Time
}
