// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Order struct {
	OrderID    int64
	CustomerID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type OrderItem struct {
	ID        int64
	OrderID   int64
	ProductID int64
	Quantity  int32
	Price     pgtype.Numeric
	Subtotal  pgtype.Numeric
}

type Product struct {
	ID          int64
	Name        string
	Price       pgtype.Numeric
	Quantity    int32
	Description string
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}
