// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id)
VALUES ($1
) RETURNING id, customer_id, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, customerID int64) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(&i.ID, &i.CustomerID, &i.CreatedAt)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price_in_cents)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price_in_cents
`

type CreateOrderItemParams struct {
	OrderID      int64
	ProductID    int64
	Quantity     int32
	PriceInCents int32
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.PriceInCents,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.PriceInCents,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT o.id, o.customer_id, o.created_at,
       json_agg(json_build_object(
           'id', oi.id,
           'product_id', oi.product_id,
           'quantity', oi.quantity,
           'price_in_cents', oi.price_in_cents
       )) AS items
FROM orders o
JOIN order_items oi ON o.id = oi.order_id
WHERE o.id = $1
GROUP BY o.id
`

type GetOrderByIDRow struct {
	ID         int64
	CustomerID int64
	CreatedAt  pgtype.Timestamptz
	Items      []byte
}

func (q *Queries) GetOrderByID(ctx context.Context, id int64) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, id)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.ID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.Items,
	)
	return i, err
}

const getOrders = `-- name: GetOrders :many
SELECT o.id, o.customer_id, o.created_at,
       json_agg(json_build_object(
           'id', oi.id,
           'product_id', oi.product_id,
           'quantity', oi.quantity,
           'price_in_cents', oi.price_in_cents
       )) AS items
FROM orders o
JOIN order_items oi ON o.id = oi.order_id
GROUP BY o.id
`

type GetOrdersRow struct {
	ID         int64
	CustomerID int64
	CreatedAt  pgtype.Timestamptz
	Items      []byte
}

func (q *Queries) GetOrders(ctx context.Context) ([]GetOrdersRow, error) {
	rows, err := q.db.Query(ctx, getOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrdersRow
	for rows.Next() {
		var i GetOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.CustomerID,
			&i.CreatedAt,
			&i.Items,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductStock = `-- name: UpdateProductStock :exec
UPDATE products
SET quantity = $2
WHERE id = $1
`

type UpdateProductStockParams struct {
	ID       int64
	Quantity int32
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error {
	_, err := q.db.Exec(ctx, updateProductStock, arg.ID, arg.Quantity)
	return err
}
