// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: orders.sql

package database

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOrder = `-- name: CreateOrder :one
INSERT INTO orders (customer_id)
VALUES ($1
) RETURNING order_id, customer_id, created_at
`

func (q *Queries) CreateOrder(ctx context.Context, customerID pgtype.UUID) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder, customerID)
	var i Order
	err := row.Scan(&i.OrderID, &i.CustomerID, &i.CreatedAt)
	return i, err
}

const createOrderItem = `-- name: CreateOrderItem :one
INSERT INTO order_items (order_id, product_id, quantity, price)
VALUES ($1, $2, $3, $4)
RETURNING id, order_id, product_id, quantity, price, subtotal
`

type CreateOrderItemParams struct {
	OrderID   int64
	ProductID int64
	Quantity  int32
	Price     pgtype.Numeric
}

func (q *Queries) CreateOrderItem(ctx context.Context, arg CreateOrderItemParams) (OrderItem, error) {
	row := q.db.QueryRow(ctx, createOrderItem,
		arg.OrderID,
		arg.ProductID,
		arg.Quantity,
		arg.Price,
	)
	var i OrderItem
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.Subtotal,
	)
	return i, err
}

const getOrderByID = `-- name: GetOrderByID :one
SELECT o.order_id, o.customer_id, o.created_at, oi.id AS order_item_id, oi.product_id, oi.quantity, oi.price, oi.subtotal, p.name AS product_name
FROM orders o
LEFT JOIN order_items oi ON o.order_id = oi.order_id
LEFT JOIN products p ON oi.product_id = p.id
WHERE o.order_id = $1
`

type GetOrderByIDRow struct {
	OrderID     int64
	CustomerID  pgtype.UUID
	CreatedAt   pgtype.Timestamptz
	OrderItemID pgtype.Int8
	ProductID   pgtype.Int8
	Quantity    pgtype.Int4
	Price       pgtype.Numeric
	Subtotal    pgtype.Numeric
	ProductName pgtype.Text
}

func (q *Queries) GetOrderByID(ctx context.Context, orderID int64) (GetOrderByIDRow, error) {
	row := q.db.QueryRow(ctx, getOrderByID, orderID)
	var i GetOrderByIDRow
	err := row.Scan(
		&i.OrderID,
		&i.CustomerID,
		&i.CreatedAt,
		&i.OrderItemID,
		&i.ProductID,
		&i.Quantity,
		&i.Price,
		&i.Subtotal,
		&i.ProductName,
	)
	return i, err
}

const getOrderItemsByOrderID = `-- name: GetOrderItemsByOrderID :many
SELECT oi.id, oi.order_id, oi.product_id, oi.quantity, oi.price, oi.subtotal, p.name AS product_name 
FROM order_items oi
JOIN products p ON oi.product_id = p.id
WHERE oi.order_id = $1
`

type GetOrderItemsByOrderIDRow struct {
	ID          int64
	OrderID     int64
	ProductID   int64
	Quantity    int32
	Price       pgtype.Numeric
	Subtotal    pgtype.Numeric
	ProductName string
}

func (q *Queries) GetOrderItemsByOrderID(ctx context.Context, orderID int64) ([]GetOrderItemsByOrderIDRow, error) {
	rows, err := q.db.Query(ctx, getOrderItemsByOrderID, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOrderItemsByOrderIDRow
	for rows.Next() {
		var i GetOrderItemsByOrderIDRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.ProductID,
			&i.Quantity,
			&i.Price,
			&i.Subtotal,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrders = `-- name: GetOrders :many
SELECT order_id, customer_id, created_at FROM orders
ORDER BY created_at DESC
`

func (q *Queries) GetOrders(ctx context.Context) ([]Order, error) {
	rows, err := q.db.Query(ctx, getOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Order
	for rows.Next() {
		var i Order
		if err := rows.Scan(&i.OrderID, &i.CustomerID, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductStock = `-- name: UpdateProductStock :exec
UPDATE products
SET quantity = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateProductStockParams struct {
	ID       int64
	Quantity int32
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) error {
	_, err := q.db.Exec(ctx, updateProductStock, arg.ID, arg.Quantity)
	return err
}
